name = "my-jsonendpoint"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2022-01-20"

kv_namespaces = [ 
  { binding = "JSONSTORAGE", id = "" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"